# Generated by Django 3.2.5 on 2024-06-03 05:50

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0002_auto_20201124_0614'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='date_of_agreement',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Anlaşma Taihi'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='address',
            field=models.TextField(blank=True, verbose_name='Adres'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='current_status',
            field=models.CharField(choices=[('active', 'Aktif'), ('inactive', 'Pasif')], default='active', max_length=10, verbose_name='Durum'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='date_of_admission',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Göreve Başlama Taihi'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Doğum Tarihi'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='firstname',
            field=models.CharField(max_length=200, verbose_name='Adı'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='gender',
            field=models.CharField(choices=[('male', 'Erkek'), ('female', 'Kız')], default='male', max_length=10, verbose_name='Cinsiyeti'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message='Girilen cep telefonu numarası doğru formatta değil!', regex='^[0-9]{10,15}$')], verbose_name='Cep Telefonu'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='other_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Anlaşılan Ücreti'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='others',
            field=models.TextField(blank=True, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='surname',
            field=models.CharField(max_length=200, verbose_name='Soyadı'),
        ),
    ]
