# Generated by Django 3.2.5 on 2024-06-03 05:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0005_auto_20240603_0850'),
        ('students', '0003_auto_20240603_0850'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='balance_from_previous_term',
            field=models.IntegerField(default=0, verbose_name='Kayıt Ücreti'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='class_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corecode.studentclass', verbose_name='Sınıf'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corecode.academicsession', verbose_name='Eğitim Yılı'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('active', 'Aktif'), ('closed', 'Kapandı')], default='active', max_length=20, verbose_name='Durum'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='Öğrenci'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corecode.academicterm', verbose_name='Dönem'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='amount_paid',
            field=models.IntegerField(verbose_name='Ödeme Miktarı'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='comment',
            field=models.CharField(blank=True, max_length=200, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='date_paid',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Ödeme Tarihi'),
        ),
    ]
