# Generated by Django 5.1 on 2024-08-25 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0005_auto_20240603_0850'),
        ('finance', '0002_auto_20240603_0850'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receipt',
            options={'get_latest_by': 'date_paid', 'ordering': ['-date_paid']},
        ),
        migrations.AlterField(
            model_name='invoice',
            name='balance_from_previous_term',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Kayıt Ücreti'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='class_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corecode.studentclass', verbose_name='Kursu'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ödeme Miktarı'),
        ),
    ]
