# Generated by Django 3.2.5 on 2024-06-03 05:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0005_auto_20240603_0850'),
        ('students', '0002_auto_20201124_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.TextField(blank=True, verbose_name='Adres'),
        ),
        migrations.AlterField(
            model_name='student',
            name='current_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corecode.studentclass', verbose_name='Sınıfı'),
        ),
        migrations.AlterField(
            model_name='student',
            name='current_status',
            field=models.CharField(choices=[('active', 'Aktif'), ('inactive', 'Pasif')], default='active', max_length=10, verbose_name='Durumu'),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_admission',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Kayıt Tarihi'),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Doğum Tarihi'),
        ),
        migrations.AlterField(
            model_name='student',
            name='firstname',
            field=models.CharField(max_length=200, verbose_name='Adı'),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('male', 'Erkek'), ('female', 'Kadın')], default='male', max_length=10, verbose_name='Cinsiyet'),
        ),
        migrations.AlterField(
            model_name='student',
            name='other_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Veli Adı'),
        ),
        migrations.AlterField(
            model_name='student',
            name='others',
            field=models.TextField(blank=True, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_mobile_number',
            field=models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message='Girilen cep telefonu numarası doğru formatta değil!', regex='^[0-9]{10,15}$')], verbose_name='Veli Telefon Numarası'),
        ),
        migrations.AlterField(
            model_name='student',
            name='passport',
            field=models.ImageField(blank=True, upload_to='students/passports/', verbose_name='Öğrenci Fotoğrafı'),
        ),
        migrations.AlterField(
            model_name='student',
            name='registration_number',
            field=models.CharField(max_length=200, unique=True, verbose_name='TC Kimlik No'),
        ),
        migrations.AlterField(
            model_name='student',
            name='surname',
            field=models.CharField(max_length=200, verbose_name='Soyadı'),
        ),
    ]
