# Generated by Django 5.1 on 2024-09-08 11:29

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IslemYapanKisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField(max_length=200, verbose_name='Adı')),
                ('soyadi', models.CharField(max_length=200, verbose_name='Soyadı')),
                ('cep_numarasi', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Girilen cep telefonu numarası doğru formatta değil!', regex='^[0-9]{10,15}$')], verbose_name='Cep Telefonu')),
            ],
            options={
                'verbose_name': 'İşlem Yapan Kişi',
                'verbose_name_plural': 'İşlem Yapan Kişiler',
            },
        ),
        migrations.CreateModel(
            name='TakipEdenKisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField(max_length=200, verbose_name='Adı')),
                ('soyadi', models.CharField(max_length=200, verbose_name='Soyadı')),
                ('cep_numarasi', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Girilen cep telefonu numarası doğru formatta değil!', regex='^[0-9]{10,15}$')], verbose_name='Cep Telefonu')),
            ],
            options={
                'verbose_name': 'Takip Eden Kişi',
                'verbose_name_plural': 'Takip Eden Kişiler',
            },
        ),
        migrations.CreateModel(
            name='Musteri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musteri_no', models.CharField(max_length=100, unique=True, verbose_name='Müşteri Numarası')),
                ('adi', models.CharField(max_length=200, verbose_name='Adı')),
                ('soyadi', models.CharField(max_length=200, verbose_name='Soyadı')),
                ('cep_numarasi', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Girilen cep telefonu numarası doğru formatta değil!', regex='^[0-9]{10,15}$')], verbose_name='Cep Telefonu')),
                ('cinsiyet', models.CharField(choices=[('erkek', 'Erkek'), ('kadın', 'Kadın')], max_length=10, verbose_name='Cinsiyet')),
                ('islem_tarihi', models.DateField(default=django.utils.timezone.now, verbose_name='İşlem Tarihi')),
                ('durum', models.CharField(choices=[('aktif', 'Aktif'), ('pasif', 'Pasif')], default='aktif', max_length=6, verbose_name='Durumu')),
                ('adres', models.TextField(blank=True, verbose_name='Adres')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('musteri_fotografi1', models.ImageField(blank=True, upload_to='musteriler/fotograflar/', verbose_name='Müşteri Fotoğrafı 1')),
                ('musteri_fotografi2', models.ImageField(blank=True, upload_to='musteriler/fotograflar/', verbose_name='Müşteri Fotoğrafı 2')),
                ('musteri_fotografi3', models.ImageField(blank=True, upload_to='musteriler/fotograflar/', verbose_name='Müşteri Fotoğrafı 3')),
                ('musteri_fotografi4', models.ImageField(blank=True, upload_to='musteriler/fotograflar/', verbose_name='Müşteri Fotoğrafı 4')),
                ('islem_yapan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='islem.islemyapankisi', verbose_name='İşlem Yapan Kişi')),
                ('takip_eden', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='islem.takipedenkisi', verbose_name='Takip Eden Kişi')),
            ],
            options={
                'verbose_name': 'Müşteri',
                'verbose_name_plural': 'Müşteriler',
                'ordering': ['soyadi', 'adi'],
            },
        ),
        migrations.CreateModel(
            name='Islem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('islem_tipi', models.CharField(max_length=200, verbose_name='İşlem Tipi')),
                ('islem_tarihi', models.DateField(default=django.utils.timezone.now, verbose_name='İşlem Tarihi')),
                ('toplam_borc', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Toplam Borç')),
                ('islem_maliyeti', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='İşlem Maliyeti')),
                ('islem_yapan_yuzde', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='İşlem Yapan Yüzdesi')),
                ('takip_eden_yuzde', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Takip Eden Yüzdesi')),
                ('islem_yapan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='islem.islemyapankisi', verbose_name='İşlem Yapan Kişi')),
                ('musteri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='islem.musteri', verbose_name='Müşteri')),
                ('takip_eden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='islem.takipedenkisi', verbose_name='Takip Eden Kişi')),
            ],
            options={
                'verbose_name': 'İşlem',
                'verbose_name_plural': 'İşlemler',
            },
        ),
    ]
