# Generated by Django 5.1 on 2024-09-08 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('islem', '0003_remove_musteri_durum_remove_musteri_islem_tarihi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musteri',
            name='musteri_no',
        ),
        migrations.AlterField(
            model_name='islem',
            name='islem_yapan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='islem.islemyapankisi', verbose_name='Uzman'),
        ),
        migrations.AlterField(
            model_name='islem',
            name='takip_eden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='islem.takipedenkisi', verbose_name='Müşteri Temsilcisi'),
        ),
    ]
