# Generated by Django 3.2.5 on 2024-06-03 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0004_auto_20201124_0614'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentclass',
            options={'ordering': ['name'], 'verbose_name': 'Sınıf', 'verbose_name_plural': 'Sınıflar'},
        ),
        migrations.AlterField(
            model_name='academicsession',
            name='current',
            field=models.BooleanField(default=True, verbose_name='Aktif Eğitim Yılı'),
        ),
        migrations.AlterField(
            model_name='academicsession',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Eğitim Yılı'),
        ),
        migrations.AlterField(
            model_name='academicterm',
            name='current',
            field=models.BooleanField(default=True, verbose_name='Aktif Dönem'),
        ),
        migrations.AlterField(
            model_name='academicterm',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='Dönem'),
        ),
        migrations.AlterField(
            model_name='studentclass',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Sınıf'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Ders'),
        ),
    ]
