# Generated by Django 3.2.5 on 2024-06-04 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='call',
            name='date_of_agreement',
        ),
    ]
