# Generated by Django 5.1 on 2024-08-25 15:36

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0002_remove_call_date_of_agreement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='date_of_interview',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Görüşme Tarihi'),
        ),
        migrations.AlterField(
            model_name='call',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message='Girilen cep telefonu numarası doğru formatta değil!', regex='^[0-9]{10,15}$')], verbose_name='Cep Telefonu'),
        ),
    ]
